### ISSUE TITLE
most ts files in dist folder have a .d in the filename

### ISSUE THREAD

**Issue by klayus** [lucassaid/react-native-cool-speedometer#10]
i installed the library with npm install ... and all the files in my dist folder have an ".d" before the .ts extension. none of those are found when importing the library. am i missing something?

**Comment by lucassaid** [comment]
Yes, those .d.ts are the declaration files that typescrit auto generates from the [src](https://github.com/lucassaid/react-native-cool-speedometer/tree/master/src) folder. They help you while using the library by showing autocompletions, warnings, etc. Are you having some error importing the library?

**Comment by klayus** [comment]
well, this morning did not work. I changed nothing and it works now :) sorry, my bad

**Comment by lucassaid** [comment]
Great, let me know if you have any other issue 🙌
