### ISSUE TITLE
Indicator Suffix Prop not working 

### ISSUE THREAD

**Issue by VictorKengoo** [lucassaid/react-native-cool-speedometer#11]
First of all, congratulations for the huge and complete library, way way better than the others i´ve searched online.
Second, I would like to point that the "suffix" property of the Indicator component is not working.

![image](https://user-images.githubusercontent.com/55894232/164816771-b440c7eb-81af-4777-ba67-e21b6e2ffc02.png)
![image](https://user-images.githubusercontent.com/55894232/164817162-88bb5be7-fccd-4fca-a358-cad1fd45d881.png)

**Comment by lsaidspace** [comment]
Wow thanks for your words 😃 I'm glad it helps. About the suffix, I forgot to remove that form the readme.... The current way to add a suffix is rendering a custom indicator:

```jsx
<Indicator>
  {(value, textProps) => (
    <Text
      {...textProps} // textProps has the "transform" property only
      fill="#555"
      x={250 / 2} // assumes that the size of the speedometer is 250 (the default size)
      y={250 / 2} // use something like 250 / 2 + 40 to place the indicator lower
      textAnchor="middle"
    >
      {value}k/m
    </Text>
  )}
</Indicator>
```

Use `Text` imported from 'react-native-svg', unless you need to add a custom font, in that case you can use `Text` from 'react-native' (see more [here](https://github.com/lucassaid/react-native-cool-speedometer/issues/9))
