### ISSUE TITLE
java.lang Double cannot be cast to abi48_0_0.com.facebook.react.bridge.ReadableMap

### ISSUE THREAD

**Issue by ikhsanadrians** [lucassaid/react-native-cool-speedometer#16]
cannot using the package if the react-native-svg in version 13.4.0

**Comment by DarwinCamahalan** [comment]
Any solution on this?, I have tried downgrading react-native-svg to version 12.4.0, still get the error.

**Comment by DarwinCamahalan** [comment]
**Solution:** Downgrade Expo SDK to 46 or 47 and the react-native-svg version should downgrade automatically to 12.3.0 and the error will be gone, avoid SDK 45 below if you want to use Expo Go it only supports version 46,47 and 48.

**Comment by ikhsanadrians** [comment]
thanks a lot, this helped me

**Comment by lucassaid** [comment]
@ikhsanadrians @DarwinCamahalan I upgraded react-native-svg to 13.9.0, I'll close this, feel free to create another issue if the error persist, thank you!
