### ISSUE TITLE
Animated speedometer demo

### ISSUE THREAD

**Issue by sumeetkg** [lucassaid/react-native-cool-speedometer#5]
Thanks Lucas for this amazing library, is there any demo on how to use needle animation on value change? I tried to use AnimatedSpeedometer but crashing when prefill value changes.

**Comment by lucassaid** [comment]
Sorry for the delay, I don't understand what is the issue, is it failing when changing the value of the Speedometer? In that case it shouldn't, the value you pass is meant to change dinamically
