### ISSUE TITLE
How to use globalLineCap

### ISSUE THREAD

**Issue by junkmaker** [lucassaid/react-native-cool-speedometer#7]
Is globalLineCap defined by myself?
I didn't understand how to use it

**Comment by lucassaid** [comment]
Hello, the idea is that you can pass a `lineCap` to `<Speedometer/>` only. Then other components  (Arc, DangerPath, Progress) will use that value. But you can also specify a different `lineCap` for those components.

For example, in this case, `<Progress />` will use "line".
```js
<Speedometer lineCap="line">
  <Progress />
</Speedometer>
```

But I can pass another value if I like
```js
<Speedometer lineCap="line">
  <Progress lineCap="square" />
</Speedometer>
```

**Comment by junkmaker** [comment]
Thanks to you, I understand now!
I didn't understand that the Context's lineCap is assigned to the globalLineCap.
